### PR TITLE
🤖 Add file patterns to config.json

### PR DESCRIPTION
**Pull request by ErikSchierboom**
**⚠ This PR requires you to make a simple change before merging. ⚠**

---

To save maintainers from having to manually specify the `files` key in their exercises' `.meta/config.json` files, we are providing support for track-level patterns. See [this PR](https://github.com/exercism/docs/pull/58) for details.

This PR adds (**purposefully wrong**) file patterns to the `config.json` file. It is up to you, the track maintainers, to change these patterns to their correct value.

You can use the following placeholders:
- `%{kebab_slug}`: the `kebab-case` exercise slug (e.g. `bit-manipulation`)
- `%{snake_slug}`: the `snake_case` exercise slug (e.g. `bit_manipulation`)
- `%{camel_slug}`: the `camelCase` exercise slug (e.g. `bitManipulation`)
- `%{pascal_slug}`: the `PascalCase` exercise slug (e.g. `BitManipulation`)

We will soon update `configlet` to enable it to automatically populate the `.meta/config.json` file's `files` property, at which point we will then batch-PR updates to all tracks that have merged this PR.

## Tracking
https://github.com/exercism/v3-launch/issues/19

### CODE REVIEW

**Review by leobenkel — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
@leobenkel This PR actually requires a change to be made :)

**Review by leobenkel — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
@leobenkel I'm sorry I wasn't clear, but what I meant was that this PR is _not_ ready to be merged as its contents should be modified by maintainers first :)

**Comment by leobenkel** [comment]
> @leobenkel I'm sorry I wasn't clear, but what I meant was that this PR is _not_ ready to be merged as its contents should be modified by maintainers first :)

Oh I understand. I think Github has a feature to mark PR as `draft`, that could avoid confusion :)

**Comment by ErikSchierboom** [comment]
Ah yes, that would have been useful. Sorry!

**Comment by MeerKatDev** [comment]
I'm not sure this is what it's required here, but in general, as far as scala with sbt is concerned, you have `src/main/scala` for the app files and `src/test/scala` for the tests. there is a `scala` part because there could be also a `java` folder there, and `main`, `test` are environments-level, so there could be a `staging` or `production` there.

**Pull request merged**
