### PR TITLE
Bump Scala to version `2.13` and scalatest to version `3.2.10`

### PR DESCRIPTION
**Pull request by CJSmith-0141**
Addresses #678 and partially addresses #684 

I also ran `configlet sync -u`, not sure if that was needed or necessary. 

I was not able to get the generation code to work, could someone help bring that home? It might need a re-write. 

Help needed on the test generation. Manually editing the tests with these changes works.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
> I also ran configlet sync -u, not sure if that was needed or necessary.

I don't think that was necessary. In fact, could you perhaps remove that commit from this PR and open a separate PR for the syncing update? The update is much appreciated, but we prefer to have PRs do just a single thing.

> I was not able to get the generation code to work, could someone help bring that home? It might need a re-write.

We currently don't have any active Scala maintainers. What I would do is to just ignore the generators now and only update the exercises.

**Comment by CJSmith-0141** [comment]
I removed the `configlet sync -u` commit and added a commit that manually updates the `org.scalatest` imports and class traits for the exercise tests. 

I think another PR to update track requirements in the documentation might be needed, or that might be in scope for this PR. Let me know.

**Comment by ErikSchierboom** [comment]
> I removed the configlet sync -u commit and added a commit that manually updates the org.scalatest imports and class traits for the exercise tests.

Perfect.

> I think another PR to update track requirements in the documentation might be needed, or that might be in scope for this PR. Let me know.

Yes, I think it makes sense to include it in this PR, as it is a related change.

**Comment by CJSmith-0141** [comment]
No worries, added my two cents to `docs/INSTALLATION.md`

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Merged! Thanks a lot.

**Comment by ErikSchierboom** [comment]
@CJSmith-0141 BTW, did you intend to try and upgrade to Scala 3 too?

**Pull request merged**
