### PR TITLE
Fixed Unit Test, missing empty string for first test case

### PR DESCRIPTION
**Pull request by brownbonnie**
I've added a small fix to get the unit tests into a compiling state.

### CODE REVIEW

**Comment by brownbonnie** [comment]
I've raised this in an issue also: https://github.com/exercism/scala/issues/708

**Comment by ErikSchierboom** [comment]
This is not actually a bug, but a feature :) The goal of this exercise is to have students use optional parameters with a default value. Hence the test without a name being passed.

**Comment by brownbonnie** [comment]
Ah very interesting, thanks. Would it be possible to add examples of default parameters in the tutorial?

**Comment by mrybak834** [comment]
Hello,

I would argue that a test not compiling is not a result of the failure of the one trying to solve the question.

The tests are supposed to be supportive units outside of the structure of the solution program.

I don't think it makes sense for a test to not compile like it does here. 
At the very least it should be mentioned somewhere.

**Comment by ErikSchierboom** [comment]
The ergonomics here are a bit odd. It might be better to convert the exercise to use an `Option[T]` parameter instead.

**Pull request closed without merging**
