### PR TITLE
[v3] Add key features to config.json

### PR DESCRIPTION
**Pull request by yzAlvin**
Hi! first time contributing, 
I hope I've done this right please let me know what to fix!

Addreses [#650 [v3] Add key features](https://github.com/exercism/scala/issues/650)

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]
This is great, thanks!

**Comment by ErikSchierboom** [comment]
@yzAlvin If you go to https://exercism.lol/tracks/scala (without having joined the track or in an incognito window), you'll see the key features being shown :)

If you're interested in making another contribution, you could look at https://github.com/exercism/scala/issues/651 Some tags were already suggested there, so I think it should be relatively easy to implement.

**Comment by yzAlvin** [comment]
Wow that is so cool!
I want to add stuff to Exercism everywhere now 😍

**Comment by ErikSchierboom** [comment]
@yzAlvin That's brilliant! If you send me an email at erik at exercism.io, I can get you up to speed :)

**Pull request merged**
